/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wordguesser;

public class Game {

    public String getWordToGuess() {
        Character firstLetter = word.charAt(0);
        String blank = "_____";
        return firstLetter+blank;
    }

    String word;
    Game(String chosenWord) {
        word = chosenWord;
    }

    public static void main(String[] args) { }
}
